name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable pnpm (via corepack)
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies (pnpm)
        run: pnpm install
        working-directory: gestion-inventario

      - name: Run linter
        run: pnpm -w --filter ./gestion-inventario lint

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable pnpm (via corepack)
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install
        working-directory: gestion-inventario

      - name: Build application
        run: pnpm build
        working-directory: gestion-inventario
        env:
          POSTGRES_USER: inventory_user
          POSTGRES_PASSWORD: inventory_pass
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: inventory_db
      services:
        postgres:
          image: postgres:16
          env:
            POSTGRES_USER: inventory_user
            POSTGRES_PASSWORD: inventory_pass
            POSTGRES_DB: inventory_db
          ports: ['5432:5432']
          options: >-
            --health-cmd pg_isready -U inventory_user -d inventory_db
            --health-interval 10s --health-timeout 5s --health-retries 5

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: .next/
          retention-days: 7

  docker:
    name: Build and Test Docker
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start PostgreSQL container (compose)
        run: |
          cd gestion-inventario
          docker compose up -d
          sleep 10

      - name: Check database health
        run: |
          cd gestion-inventario
          docker compose ps
          docker compose logs postgres || true

      - name: Test database connection
        run: |
          docker exec inventory-db pg_isready -U inventory_user -d inventory_db || true

      - name: Stop containers
        run: |
          cd gestion-inventario
          docker compose down

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, docker]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .next/

      - name: Deploy notification
        run: |
          echo "Ready to deploy to production"
          echo "Build completed successfully"
